service: doi-pdf-api

# Update memory size for Lambda to handle PDF processing
provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 1024 # Increase memory size for PDF processing
  timeout: 60 # Increase timeout for longer processing
  logRetentionInDays: 30
  environment:
    NODE_ENV: ${self:provider.stage}
    CACHE_ENABLED: true
    CACHE_TTL: 86400 # 24 hours in seconds
    RATE_LIMIT_WINDOW_MS: 60000 # 1 minute
    RATE_LIMIT_MAX_REQUESTS: 10 # 10 requests per minute

functions:
  api:
    handler: src/lambda.handler
    events:
      - http:
          path: /api/{proxy+}
          method: any
          cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
