service: doi-pdf-api

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 2048
  timeout: 30
  environment:
    NODE_ENV: ${self:provider.stage}
    CACHE_ENABLED: "true"
    CACHE_TTL: "86400"
    RATE_LIMIT_WINDOW_MS: "60000"
    RATE_LIMIT_MAX_REQUESTS: "10"
    TEXT_EXTRACTION_ENABLED: "true"
  logRetentionInDays: 14

functions:
  api:
    handler: src/lambda.handler
    events:
      - http:
          path: /api/{proxy+}
          method: any
          cors: true

plugins:
  - serverless-esbuild
  - serverless-offline

package:
  individually: true

custom:
  esbuild:
    bundle: true
    minify: ${self:provider.stage == 'prod', false}
    sourcemap: ${self:provider.stage != 'prod', true}
    exclude:
      - aws-sdk
    external:
      - pdf-parse
    platform: node
    target: node18
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true
